#for creating the java classes from the pel json file
import json
import os

#creates the enum classes for each of the power usages in the json file
file = open("pel.json", "r")
data = json.load(file)
path = "src/main/java/demosystem/models/pel"
powerList = data["power_loads"]
for item in powerList:
    oName = item["name"]
    fName = item["name"] + "_State"
    filepath = os.path.join(path, fName + ".java")
    newF = open(filepath, "w")
    stateList = []
    loadList = []
    for ent in item["power_states"]:
        stateList.append(ent["state"].upper())
        loadList.append(ent["power_usage"]["value"])
    body = f"""package demosystem.models.pel;

/**
 * This class was created by the pel_java_generator.py script and represents the state(s) of the {oName} as an enum and associates
 * a power load amount to each state.
 */

public enum {fName} {{
"""
    for num in range(len(stateList)):
        if num != (len(stateList) - 1):
            state = stateList[num].upper()
            body = body + "\t" + state + "(" + str(loadList[num]) + ")" + ",\n"
        else:
            state = stateList[num].upper()
            body = body + "\t" + state + "(" + str(loadList[num]) + ");"+ "\n"
    newF.write(body)
    constructor = f"""    private final double load;
    {fName}(double load) {{
        this.load = load;  //in Watts
    }}

    /**
     * Function that returns the load of state of the instrument.
     * @return the power needed for that state
     */
    public double getLoad() {{
        return load;  
    }}
}}
    """
    newF.write(constructor)
    newF.close()


#making a Pel model class that contains an instance of the power usage enum classes and this class interacts with the Battery class
pelPath = os.path.join(path, "PELModel.java")
pelFile = open(pelPath, "w")
initial = f"""package demosystem.models.pel;

import gov.nasa.jpl.aerie.merlin.framework.Registrar;
import gov.nasa.jpl.aerie.contrib.serialization.mappers.EnumValueMapper;
import powersystem.SettableState;
import powersystem.DerivedState;

/**
 * This class is generated by the pel_java_generator.py script, and it represents the PEL and contains all the
 * possible power loads of the spacecraft and registers them as resources.
 */
public class PELModel {{

    public DerivedState<Double> totalLoad;
"""

construct = f"""    public PELModel() {{
"""
load = f"""        this.totalLoad = DerivedState.builder(Double.class)
                .sourceStates("""
compute = f"""    /**
     * Computes the power load of the spacecraft so the battery will be discharged accordingly, value changes whenever
     * the states of the instruments change
     * @return the power load of the spacecraft
     */
    public double computeLoad() {{
        return """

register = f"""    public void registerStates(Registrar registrar) {{
"""
for x in range(len(powerList)):
    name = powerList[x]["name"]
    initial = initial + "\tpublic SettableState<" + name + "_State> " + name.lower() + "State;\n"

    stateName = powerList[x]["power_states"][0]["state"].upper()
    construct = construct + "\t\tthis." + name.lower() + "State = SettableState.builder(" + name + "_State.class).initialValue(" + name + "_State." + stateName + ").build();\n"
    if x == (len(powerList) - 1):
        load = load + "this." + name.lower() + "State)\n\t\t\t\t.valueFunction(this::computeLoad)\n\t\t\t\t.build();"
        compute = compute + "this." + name.lower() + "State.get().getLoad();\n\t}\n"
    else:
        load = load + "this." + name.lower() + "State, "
        compute = compute + "this." + name.lower() + "State.get().getLoad() + "

    register = register + "\t\tregistrar.discrete(\"" + name.lower() + "State\"," + name.lower() + "State, new EnumValueMapper<>(" + name + "_State.class));\n"

    if x == (len(powerList) - 1):
        construct = construct + load + "\n\t}\n"
        register = register + "\t}\n}"
pelFile.write(initial)
pelFile.write(construct)
pelFile.write(compute)
pelFile.write(register)
pelFile.close()



                
                
            
                        
        
